Fix homepage
austinmargarone/portfolio pull request #18
Opened 2023-09-18 14:57 UTC by austinmargarone

2023-09-18 16:00 UTC, brandonetter requested changes
Looks much better on the services section, I would suggest changing the breakpoint to be a little later though, as it still becomes very narrow all the way until 1700px wide. Good decision to make it change shape at smaller screens- but it changes way before we even hit the figma design width.

![image](https://github.com/austinmargarone/portfolio/assets/4108484/7f0f9be7-8e19-4162-8de2-737d41cf8dbd)

"Portfolio" should be renamed to "Case studies" I think, and the width and spacing is questionable there, as well. I think you should change the breakpoint to before 1700px wide as there is a ton of empty space.

![image](https://github.com/austinmargarone/portfolio/assets/4108484/02b9f72f-a4b1-48d7-8081-11c8a034abf7)

Your cards on the homepage no longer have the image cut-off on the right, which is fine. But they also no longer have centered text vertically. The image and text to the left are vertically misaligned:

![image](https://github.com/austinmargarone/portfolio/assets/4108484/e7308538-59fe-48d5-ba6e-f13a00d71a1e)

Other than that this is coming along great. I'll send you the sanity cli link

2023-09-18 16:05 UTC, brandonetter requested changes

2023-09-18 16:05 UTC, brandonetter commented on components/homepage/Hero.tsx
>          <Image src="/Hero.svg" width={757} height={541} alt="Hero computers" />
```suggestion
        <Image src="/Hero.svg" width={757} height={541} alt="Hero computers" priority/>
```
This hero image is the main image you want to load as the website renders. So label it as priority to optimize page load.

https://nextjs.org/docs/pages/building-your-application/optimizing/images

![image](https://github.com/austinmargarone/portfolio/assets/4108484/34926c3f-e3a5-4d7d-bd0b-f2303fbca60e)

2023-09-18 16:27 UTC, austinmargarone commented
@brandonetter For confirmation you're referring to the mobile size switching to medium sooner? How do i go about this? I've been trying to implement this but unsuccessful.

2023-09-18 17:12 UTC, austinmargarone commented
@brandonetter Does this look better?

2023-09-18 20:42 UTC, brandonetter commented
@austinmargarone Case studies looks perfect. For the services it looks much better at 1460 - 1700, but below that you can keep what you were doing to make it two across if you'd like. To be clear I wasn't saying your method of grouping was wrong- just that you should do it at a different width.

## Next:
![image](https://github.com/austinmargarone/portfolio/assets/4108484/9b17c35d-e9bb-4899-9fe2-74efb0e97aa9)

The text is now lined up vertically with the image. Good work. But it looks a little strange with the lack of padding to the right of the image if there's no overflow. It's also not really proportioned correctly- there's way more vertical empty space in yours than the design. Look at them side by side:

![image](https://github.com/austinmargarone/portfolio/assets/4108484/86e09221-d4e3-470f-a72c-7ac3ab2630fd)

2023-09-18 21:05 UTC, brandonetter commented
Here's with a couple changes and using the overflow again:

![image](https://github.com/austinmargarone/portfolio/assets/4108484/8e3eb0d8-f313-4645-8b6c-77743aeed968)


Same changes without using the overflow if you removed it because you didn't like it:

![image](https://github.com/austinmargarone/portfolio/assets/4108484/ad82385f-546b-41c2-bfbe-9a648eadb967)


I like the color choice of the golden/yellow with the deep blue. Looks great!

2023-09-18 21:07 UTC, brandonetter commented
Getting even narrower also looks pretty good in my opinion. Preferably you just follow the design given- but if you want to deviate a ton like this please try to center items and keep things aligned.

![image](https://github.com/austinmargarone/portfolio/assets/4108484/851b16f4-25cf-48c6-a51a-2cf0148382e8)

2023-09-19 19:28 UTC, austinmargarone commented
@brandonetter How's this look?

2023-09-19 23:49 UTC, merged

2023-09-19 23:49 UTC, brandonetter commented
I like it- especially the final mobile version looks clean:
![image](https://github.com/austinmargarone/portfolio/assets/4108484/cfb16c14-bb9d-4dd9-bda3-8236b991758c)


Good work.