Feat project page
austinmargarone/portfolio pull request #20
Opened 2023-09-20 18:13 UTC by austinmargarone

2023-09-20 23:11 UTC, brandonetter commented
Do you want me to merge this? We discussed fixing the design image to extend to the full width of the screen. You can either set the width of all it's containers to full (currently it's getting shortened because of it's parent sections), and then you can stretch it to full:

Or you can make it absolute to "break it out" of the width restrictions- just be mindful of positioning.

2023-09-20 23:22 UTC, brandonetter requested changes

2023-09-20 23:22 UTC, brandonetter commented on components/projects/Design.tsx
> +          height={209}
https://drive.google.com/file/d/1qSEEfn02wqwopeFK9HZksAzeWi8iUcKg/view?usp=sharing

2023-09-21 12:40 UTC, austinmargarone commented
@brandonetter I had just ran out of time, working on it now. Thanks for sending the video.

2023-09-21 14:15 UTC, austinmargarone commented
@brandonetter How does this look? I set different heights at varying breakpoints. I'd like to throw the breakpoints into globals but am not sure how to transfer the tailwind syntax to CSS.
ex. turn md:max-w-[70rem] into CSS

2023-09-21 14:39 UTC, austinmargarone commented
Can you also take a look at this for me? The heading in OtherCases.tsx is not staying within the breakpoints and I'm not sure why. 
![Screenshot from 2023-09-21 10-36-28](https://github.com/austinmargarone/portfolio/assets/123497938/596892bb-33b2-459a-b515-242fcce4b5ee)

2023-09-22 02:04 UTC, brandonetter commented
@austinmargarone 

https://github.com/austinmargarone/portfolio/assets/4108484/eb7aced2-751c-4201-bf14-2e6c6e9b50bd

Not sure what you're asking about. Your breakpoints are working. I added a blue and red border to the header for the different classes. What do you expect to happen and I can help you.

2023-09-22 13:53 UTC, austinmargarone commented
The one heading Other Case Studies I believe should be inline with the cards. On larger devices it drifts off to the left. 
![Screenshot from 2023-09-22 09-35-23](https://github.com/austinmargarone/portfolio/assets/123497938/120cef92-a5ed-4b70-9b74-47d5cd85a5cf)
![Screenshot from 2023-09-22 09-35-00](https://github.com/austinmargarone/portfolio/assets/123497938/30abc104-b52f-4691-8409-511e9500b0dd)
![Screenshot from 2023-09-22 09-34-48](https://github.com/austinmargarone/portfolio/assets/123497938/79954b06-d86e-4814-9cd0-6e8d3286f339)

2023-09-22 14:08 UTC, austinmargarone commented
@brandonetter 
Never mind I got it to look a lot better with padding.

2023-09-22 14:08 UTC, merged

2023-09-22 15:10 UTC, brandonetter commented
Great @austinmargarone